### PR TITLE
Adding a code quality badge and various small improvements

### PR DESCRIPTION
**Pull request by StardustGogeta**
Currently, the README is still linked to the repository under my account. In order to fix this, @rschwa6308 must go to [this website](https://bettercodehub.com), link their GitHub account, ask to evaluate this repository, then modify the relevant link in the README.md file. For a demonstration of the working final result, simply view my fork of the project.

Finally, please tell me if the "original" attribute of body properties windows had any purpose. I deleted it, as I could not find a use for it.

### CODE REVIEW

**Comment by rschwa6308** [comment]
The web page you provided says that "there isn't anything to compare" and it seems as if I have no way of selecting the README.md file in question.  What exactly is the problem? It looks to me like the README belongs to the master branch of my fork.

**Comment by StardustGogeta** [comment]
Sorry, the link was broken. Try it now, it is a code review website. The README badge is directed to my repository, not yours.

**Comment by rschwa6308** [comment]
It does seem as if the "original" attribute was unnecessary.  A vestigial feature of code long gone...

**Comment by rschwa6308** [comment]
I changed the url in the README to include my username, instead of yours.  Did that fix the issue? (btw this is a great idea!)

**Comment by StardustGogeta** [comment]
Thank you! 😄 Yes, I think that fixed it. If you do not already have it turned on, you can go to the website and activate pull request analysis to have it check all pull requests for their impact on the quality score.

**Pull request merged**
